spring.datasource.url=jdbc:postgresql://db.suiqyzpkhospehjxhfrl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Naruto@82815523
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect