@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "Manages personal finances")
System(financeSystem, "Finance System", "Tracks income and expenses")

System_Ext(bankApp, "Bank App", "Generates transaction notifications")
System_Ext(emailClient, "Email Client", "Receive messages")

Rel(user, financeSystem, "Records and views transactions")
Rel(financeSystem, bankApp, "Authenticate and fetches transactions")
Rel(financeSystem, emailClient, "Delivers messages")


@enduml