spring.application.name=transaction-service

server.port=8081

# Configuração do PostgreSQL (docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- OAuth2 Client Registration ---
spring.security.oauth2.client.registration.cognito.client-id=6q3ccqnr66shn0uifvabm0i105
spring.security.oauth2.client.registration.cognito.client-secret= 1vmcs373nl1gfp6848ghonpjoqifq78lidbggt4ajoa2v4aoo3vs
spring.security.oauth2.client.registration.cognito.scope=email,openid
spring.security.oauth2.client.registration.cognito.redirect-uri=spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8081/login/oauth2/code/cognito

# --- OAuth2 Provider Details ---
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_mTp4QaFas
spring.security.oauth2.client.provider.cognito.user-name-attribute=email